# Generated by Django 6.0.6 on 2026-06-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Proyek')),
                ('description', models.TextField(verbose_name='Deskripsi Proyek')),
                ('tags', models.CharField(help_text='Contoh: Django, Python, HTML', max_length=200, verbose_name='Tags (Pisahkan dengan koma)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyek',
                'verbose_name_plural': 'Proyek-Proyek',
                'ordering': ['-created_at'],
            },
        ),
    ]
