# Generated by Django 6.0.6 on 2026-06-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portofolio', '0002_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Posisi / Peran')),
                ('company', models.CharField(max_length=200, verbose_name='Perusahaan / Institusi')),
                ('start_date', models.CharField(max_length=50, verbose_name='Waktu Mulai (misal: Jan 2023)')),
                ('end_date', models.CharField(max_length=50, verbose_name='Waktu Selesai (misal: Sekarang)')),
                ('description', models.TextField(verbose_name='Deskripsi Pekerjaan')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan Tampilan')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(blank=True, verbose_name='Tentang Saya')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='File CV (PDF/Word)')),
            ],
        ),
    ]
