# Generated by Django 6.0.6 on 2026-06-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portofolio', '0003_experience_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200, verbose_name='Gelar/Jurusan')),
                ('institution', models.CharField(max_length=200, verbose_name='Nama Institusi/Universitas')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi/Prestasi')),
                ('start_year', models.CharField(max_length=4, verbose_name='Tahun Mulai')),
                ('end_year', models.CharField(blank=True, max_length=4, verbose_name="Tahun Lulus (Atau 'Sekarang')")),
            ],
            options={
                'verbose_name_plural': 'Pendidikan',
            },
        ),
    ]
