# Generated by Django 6.0.6 on 2026-06-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portofolio', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Penghargaan')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi (Opsional)')),
                ('image', models.ImageField(upload_to='awards/', verbose_name='Gambar/Sertifikat')),
                ('date', models.CharField(blank=True, max_length=50, verbose_name='Tanggal/Tahun')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Penghargaan',
                'verbose_name_plural': 'Penghargaan',
                'ordering': ['-created_at'],
            },
        ),
    ]
