# Generated by Django 6.0.6 on 2026-06-11 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portofolio', '0005_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_media/', verbose_name='File Media')),
                ('media_type', models.CharField(choices=[('image', 'Gambar'), ('video', 'Video')], default='image', max_length=10, verbose_name='Jenis Media')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app_portofolio.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
