# Generated by Django 6.0.6 on 2026-06-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portofolio', '0006_projectmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmedia',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Eksternal (Google Drive / YouTube)'),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_media/', verbose_name='File Media (Kosongkan jika pakai link)'),
        ),
    ]
